version: '3.8'

services:
  socket-dev:
    build:
      context: .
    container_name: socket_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
